baseURL = "http://example.org/"
languageCode = "zh-cn"
title = "Chen Xiaohua's Site"
theme = "novela"

paginate = 6

pygmentsstyle='monokai'

[taxonomies]
  category = "categories"

[social]
  twitter="#"
  github="#"
